fix: Fail summarize job if any plan fails (#16)

diff --git a/.github/workflows/reusable-terraform-pr.yml b/.github/workflows/reusable-terraform-pr.yml
--- a/.github/workflows/reusable-terraform-pr.yml
+++ b/.github/workflows/reusable-terraform-pr.yml
@@ -580,6 +580,15 @@ jobs:
           body-file: ${{ steps.summary.outputs.file }}
           edit-mode: replace
 
+      - name: Fail if any plan failed
+        env:
+          PLAN_SUCCESS: ${{ steps.summary.outputs.success }}
+        run: |
+          if [ "$PLAN_SUCCESS" != "true" ]; then
+            echo "🚨One or more Terraform plans failed" >&2
+            exit 1
+          fi
+
   automerge:
     name: Automerge
     if: >-
